config/routes.rb
Rails.application.routes.draw do
  get 'testimonials/index'
  get 'testimonials/new'
  get 'testimonials/create'
  devise_for :users
  root to: 'pages#home'
  
  resources :articles
  resources :testimonials
  resources :contacts, only: [:new, :create]
  get 'o_mnie', to: 'pages#o_mnie'
  get 'kontakt', to: 'pages#kontakt'
  get 'dlaczego_warto_zaufac', to: 'pages#dlaczego_warto_zaufac'
  get 'oferta', to: 'pages#oferta'
  get 'blog', to: 'pages#blog'
  get 'portfolio/teksty_reklamowe', to: 'pages#teksty_reklamowe'
  get 'portfolio/artykuly', to: 'pages#artykuly'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :rich_body
    has_one_attached :cover

    self.per_page = 6
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name, :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message,   :validate => true
    attribute :nickname,  :captcha  => true
  
    def headers
      {
        :subject => "Contact Form",
        :to => "karolinalangner1@gmail.com",
        :from => %("#{name}" <#{email}>)
      }
    end
  end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
    attribute :content, :validate => true
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def default_url_options
        { host: ENV["DOMAIN"] || "localhost:3000" }
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except:  %i[ index show ]


  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page])
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_path(@article.id, notice: "Utworzono artykuł 🎉") }
        format.json { render :show, status: :created, location: article_path(@article.id) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_path(@article.id, notice: "Zaktualizowano artykuł 🌴") }
        format.json { render :show, status: :ok, location: article_path(@article.id) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to blog_path, notice: "Artykuł został usunięty 🧀" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :cover, :tagline, :rich_body)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new 
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      ContactMailer.new_request(@contact.id)
      flash.now[:error] = nil
      redirect_to kontakt_path, notice: 'Wiadomość została wysłana'
    else
      flash.now[:error] = 'Nie udało się wysłać wiadomości'
      render 'pages/kontakt'
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def kontakt
    @contact = Contact.new
  end

  def dlaczego_warto_zaufac
    @testimonials = Testimonial.all
  end
  
  # Portfolio kategorie

  def teksty_reklamowe
    #pokaz wszystkie teksty (Tekst.all) gdzie kategoria = "reklama"
  end

  def blog
    @articles = Article.paginate(page: params[:page])
  end

  
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :authenticate_user!, except:  %i[ index ]
  def new
    @testimonial = Testimonial.new
  end

  def create
    @testimonial = Testimonial.new(testimonial_params)
      if @testimonial.save
        redirect_to dlaczego_warto_zaufac_path
      else
        flash[:alert] = "Błąd"
        render :new
      end  
  end

  def destroy
    @testimonial = Testimonial.find(params[:id])
    @testimonial.destroy
    redirect_to dlaczego_warto_zaufac_path
  end

  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  def update
    @testimonial = Testimonial.find(params[:id]) 
    @testimonial.update(testimonial_params)
    redirect_to dlaczego_warto_zaufac_path
  end

  private
  def testimonial_params
    params.require(:testimonial).permit(:author, :content, :company, :link)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>

  <!-- [...] -->

  <div class="form-inputs">
    <%= f.input :title, label: "Tytuł" %>
  </div>
  <div class="form-inputs">
    <%= f.input :tagline, hint: "Tagline, pojawi sie pod tytulem na karcie posta, na stronie bloga" %>
  </div>
  <div class="form-inputs">
    <%= f.input  :cover, as: :file, hint: "Okladka dla posta, pojawi się też pod tytułem na stronie posta" %>
  </div>


  <!-- insert these three line of code below -->
  <div class="form-inputs">
    <%= f.rich_text_area :rich_body %>
  </div>

  <div class="form-actions">
  <br><br>
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/articles/_index.html.erb
 

<div class="main-container">
  <div class="header left">
      <h2>Blog</h2>
  </div>

  <div class="right">
  <p id="notice"><%= notice %></p>
    <div class="cards">
     
      <% @articles.sort.reverse.each do |article| %>
        <div class="card-article">
          <% if article.cover.attached? %>
            <%= link_to(cl_image_tag(article.cover.key, width: 330, height: 250, crop: :fill), article) %>
          
          <% end %>
          <div class="article-title">
            <div class="date">
              <small><%= article.created_at.strftime("%d/%m/%Y") %></small>
            </div>
            <h3><%= link_to article.title, article %></h3>
          </div>
          <div class="tagline">
            <p class="text"><%= article.tagline %></p>
          </div>
          <small><%= link_to "Czytaj >>", article %></small>
        <% if user_signed_in? %>
        <div>
          <%= link_to 'Edytuj', edit_article_path(article), class:" btn btn-success" %>
          
          <%= link_to 'Usuń', article, class:" btn btn-success", method: :delete, data: { confirm: 'Na pewno?' } %>
        </div>
        <% end %>
        </div>  
      <% end %>
  
    </div>

    <div class="text-center">
      <p> <%= will_paginate @articles, :previous_label=> '<<', next_label: '>>' %> </p>
    </div>
  </div>
</div>
  <br>
  <% if user_signed_in? %>
  <div >
    <%= link_to 'Nowy artykuł', new_article_path, class:" btn btn-success" %>
  <% end %>

app/views/articles/edit.html.erb
<h1>Edytuj artykuł</h1>

<%= render 'form', article: @article %>

<%= link_to 'Pokaż ', @article %> |
<%= link_to 'Wróć', blog_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="main-container">

  <div class="header left">
      <h2>Blog</h2>
  </div>

  <div class="right">
    <div class="cards">
      <% @articles.sort.reverse.each do |article| %>
        <div class="card-article">
          <% if article.cover.attached? %>
            <%= cl_image_tag article.cover.key, width: 330, height: 250, crop: :fill %>
          <% end %>
          <div class="article-title">
            <small class="date"><%= article.created_at.strftime("%d/%m/%Y") %></small>
            <h3><%= link_to article.title, article %></h3>
          </div>
          <p class="text"><%= article.tagline %></p>
          <small><%= link_to "Czytaj >>", article %></small>
        <% if user_signed_in? %>
        <div>
          <%= link_to 'Edytuj', edit_article_path(article), class:" btn btn-success" %>
          
          <%= link_to 'Usuń', article, class:" btn btn-success", method: :delete, data: { confirm: 'Na pewno?' } %>
        </div>
        <% end %>
        </div>  
      <% end %>
  
    </div>

    <div class="text-center">
      <p> <%= will_paginate @articles, :previous_label=> '<<', next_label: '>>' %> </p>
    </div>
  </div>
</div>
  <br>
  <% if user_signed_in? %>
  <div >
    <%= link_to 'Nowy artykuł', new_article_path, class:" btn btn-success" %>
  <% end %>

app/views/articles/new.html.erb
<h1>Nowy artykuł</h1>

<%= render 'form', article: @article %>

<%= link_to 'Wróć', blog_path %>

app/views/articles/show.html.erb
<p class="text-center" id="notice"><%= notice %></p>
<p class="text-center"><small><%= @article.created_at.strftime("%d/%m/%Y") %></small></p>

<h3 class="text-center "><%= @article.title %></h3>

<div class="cover text-center mt-4">
  <% if @article.cover.attached? %>
    <%= cl_image_tag @article.cover.key, height: 400, crop: :fill %>
  <% end %>
  <p class="text text-center"><%= @article.rich_body %> </p>
</div>

<div class="share-links">
  <p class="text"><small>Podziel się:</small><br><br></p>
 <div id="fb-root"></div>
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v10.0" nonce="lS7pqvWt">
    const fbButton = document.querySelector('.fb-share-button')
    fbButton.addEventListener("click", (event) => {
      event.currentTarget.data-layout.value = window.location.href;
     });
  </script>
  <div class="fb-share-button" data-href="" data-layout="button" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Udostępnij</a></div>
  <%= twitter_button %>
  <%= linkedin_button %>
 <script language="javascript">
        function emailCurrentPage(){
            window.location.href="mailto:?subject="+document.title+"&body="+escape(window.location.href);
        }
    </script>
    <a href="javascript:emailCurrentPage()"><i style="font-size:22px;"class="fas fa-envelope-square"></i></a>
</div>
<% if user_signed_in? %>
<div>
  <%= link_to 'Edytuj', edit_article_path(@article) %> |
  <%= link_to 'Powrót do bloga', blog_path %>
</div>
<% end %>

app/views/contacts/_contact_form.html.erb
<%= form_for @contact, url: contacts_path do |f| %>
  <div>
    <%= f.text_field  :name, required: true, class: "contacts-form-text-area", placeholder: "Your Name" %><br>
    <%= f.text_field :email, required: true, class: "contacts-form-text-area", placeholder: "Your E-mail Address" %><br>
    <%= f.text_area :message,
                    rows: 8,
                    cols: 40,
                    required: true,
                    class: "contacts-form-text-area",
                    placeholder: "Your Message"%><br>

    <div class= "hidden d-none">
      <%= f.text_field :nickname %>
    </div>

    <%= f.submit 'Send Message', class: 'btn-send' %>
  </div>
<% end %>

app/views/contacts/_new.html.erb
<%= simple_form_for @contact do |f| %>
    <% if flash[:error].present? %>
        <p> flash[:error]</p>
    <% end %>
    <div class="form-inputs">
         <%= f.input :name, required: true, label: "Imię i nazwisko" %>
    </div>
    <div class="form-inputs">
        <%= f.input :email, required: true  %>
    </div>
    <div class="d-none">
        <%= f.input :nickname %>
    </div>
    <div class="form-inputs">
        <%= f.input :message, as: :text, label: "Wiadomość" %>
    </div>
    <div class="form-actions">
        <%= f.submit 'Wyślij wiadomość', class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/contacts/index.html.erb
<%= stylesheet_link_tag "contacts" %>

<div class="cont">
  <div class="map">
  <p>Google Map Link you can insert here<p>
  </div>
  <div class="contact-form">
    <h1 class="title">Contact Me</h1>
    <h2 class="subtitle">Please use form below</h2>
    <%= render 'contact_form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Patrycja Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <!--NAVBAR -->
    <div class="navbar" id="navbar">
      <div class="logo">
       <%= link_to(image_tag("logo.png", crop: :fill, class:"logoimg"), root_path) %>
      </div>
      <div class="social">
        <a href="#"><i class="fab fa-linkedin"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
      </div>
      <div class="navbar-menu" >
        <%= link_to "O mnie", o_mnie_path, class: "btn menu-item" %>
        <%= link_to "Dlaczego warto mi zaufać?", dlaczego_warto_zaufac_path, class: "btn menu-item" %>
        <div class="dropdown" style="display: none;">
          <button class="btn menu-item dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Portfolio
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <%= link_to "Teksty reklamowe", portfolio_teksty_reklamowe_path, class:"dropdown-item" %>
            <%= link_to "Artykuly", portfolio_artykuly_path, class:"dropdown-item" %>
          </div>
        </div>
        <%= link_to "Oferta", oferta_path, class: "btn menu-item" %>
        <%= link_to "Blog", blog_path, class: "btn menu-item" %>
        <%= link_to "Kontakt", kontakt_path, class: "btn menu-item" %>
      </div>
    </div>
  <!--  container -->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container" style="">
  
  <span></span>
      <%= yield %>
  </div>

  <!-- footer -->

  <div class="footer">
    <div class="columns">
      <div class="contact mt-1">
        <p>PATRYCJA HAMPELSKA <br>COPYWRITING, EDYTORSTWO I TRANSKRYPCJE </p>
        <p><i class="fas fa-phone-alt"></i><a href="tel://044589854412"> 0044589854412</a></p>
        <p><i class="fas fa-at"></i><a href="mailto:abcabc@mail.com"> abcabc@mail.com</a></p>
      </div>
      <div class="page-map mt-1">
        <ul><small>
          <p><u>Na skróty</u></p>
          <li><%= link_to "O mnie", o_mnie_path %></li>
          <li><%= link_to "Dlaczego warto mi zaufać?", dlaczego_warto_zaufac_path %></li>
          <li><%= link_to "Oferta", oferta_path %></li>
          <li><%= link_to "Blog", articles_path %></li>
        </small></ul>
      </div>
      <div class="page-map mt-1 d-none"> 
        <ul><small>
          <p><u>Portfolio</u></p>
          <li><%= link_to "Teksty reklamowe", portfolio_teksty_reklamowe_path %></li>
          <li><%= link_to "Kolejna kategoria", "#" %></li>
          <li><%= link_to "Kolejna kategoria", "#" %></li>
        </small></ul>
      </div>
      <div class="page-map mt-1"> 
        <ul><small>
          <p><u>Ostatnio na blogu</u></p>
          <% articles = Article.all %>
          <% articles.last(3).sort.reverse.each do |article| %>
          <li><%= link_to article.title, article %></li>
          <% end %>
        </small></ul>
      </div>
    </div>
    <div><p class="text-center p-0 mt-2"><small>&copy; 2021 <%= link_to "Karolina Langner", "https://karolinalangner.me" %></small></p></div>
    <div>
      <% if user_signed_in? %>
        <p class="text-center"><%= link_to "Wyloguj", destroy_user_session_path, method: :delete %> </p>
        <p class="text-center"><%= link_to "Dodaj referencje", new_testimonial_path %> </p>
        <p class="text-center"><%= link_to "Aktualizuj portfolio", "#" %> </p>
      <% end %>
    </div>
  </div>

  </body>
</html>

app/views/pages/artykuly.html.erb
<div class="main-container">
    <div class="header left">
        <h2>Artykuły</h2>
    </div>
    <div class="right">
        <div class="cards">
            <div class="card-portfolio fade-in">
                <div class="card-title">
                    <h4>Tytul pracy</h4>
                </div>
                <div class="firma">
                    </p>logo firmy</p>
                </div>
                <div class="card-body">
                    <p>Opis pracy / tagline</p>
                    <p><%= link_to "Zobacz", "#" %> </p>
                </div>
            </div>
            <div class="card-portfolio fade-in">
                <div class="card-title">
                    <h4>Coca-Cola</h4>
                </div>
                <div class="firma">
                    <img src="https://1000logos.net/wp-content/uploads/2016/11/Coca-Cola-Logo-500x500.png">
                </div>

                <div class="card-body">
                    <p>Opis pracy / tagline</p>
                    <p><%= link_to "Zobacz", "#" %> </p>
                </div>
            </div><div class="card-portfolio fade-in">
                <div class="card-title">
                    <h4>Coca-Cola</h4>
                </div>
                <div class="firma">
                    <img src="https://1000logos.net/wp-content/uploads/2016/11/Coca-Cola-Logo-500x500.png">
                </div>

                <div class="card-body">
                    <p>Opis pracy / tagline</p>
                    <p><%= link_to "Zobacz", "#" %> </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/blog.html.erb
<%= render "articles/index" %>

app/views/pages/dlaczego_warto_zaufac.html.erb
<div class="main-container">
    <div class="left header">
        <h2>Dlaczego warto mi zaufać?</h2>
    </div>

    <div class="right">
        <div class="text-left">
        <h4>Mogę zapewnić, że moje teksty są:</h4>
        <br>
            <div class="fade-in card-body text"><p><i class="fas fa-pen-nib"></i><strong> oryginalne </strong>, ponieważ nie stosuję utartych sloganów</p> </div>
            <div class="fade-in card-body text"><p><i class="fas fa-pen-nib"></i><strong> interesujące</strong> i <strong>lekkie w odbiorze</strong> - dowodzą tego opinie moich Klientów</p> </div>
            <div class="fade-in card-body text"><p><i class="fas fa-pen-nib"></i><strong> poprawne </strong> pod względem stylistycznym, gramatycznym i interpunkcyjnym</p> </div>
     
        </div>
        <br><br>
            <p class= "fade-in">Inni o mnie:</p>
            <% @testimonials.each do |testimonial| %>
            <div class="quote fade-in m-3" style="width:90%;">
                <div style="display:flex; width:100%;">
                    <i class="fas fa-quote-left"></i><p class="text text-center mx-2" style="width:100%"><em><%= testimonial.content %> </em></p> <i class="fas fa-quote-right"></i>
                </div> 
                <% if user_signed_in? %>
                    <div class="text-right">
                        <small><%= link_to "Usuń", testimonial_path(testimonial), method: :delete %></small>
                        <small><%= link_to "Edytuj", edit_testimonial_path(testimonial) %></small>
                    </div>
                <% end %>
                <p class="text-center text"> ~ <%= testimonial.author if testimonial.author? %>
                    <% if testimonial.company? && testimonial.link? %>
                        - <%= link_to testimonial.company, testimonial.link %>
                    <% elsif testimonial.company? %>
                        - <%= testimonial.company %>
                    <% end %>
                </p>
            </div>
            <%end%>

    </div>
</div>

app/views/pages/home.html.erb
<div class="main-container">
    <div class="header left">
        <h2>Uslugi copywriter</h2>
    </div>

    <div class="right">
        <h4>Hello there</h4>
        <img class="fade-in" src="https://images.pexels.com/photos/4067126/pexels-photo-4067126.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" style="width:100%; height:300px;
    object-fit: cover;margin:25px 0;">
        <p class="text">
        Współpracuję z właścicielami i managerami firm, marketerami, agencjami reklamowymi oraz wszystkimi osobami, które chcą rozwijać biznes i zarabiać więcej.
        Do tej pory pomogłem ponad 510 klientom w komunikacji, budowaniu marek, pozycjonowaniu stron i generowaniu większej sprzedaży.</p>
        <br><br>
        <p>Poszukujesz copywritera? <%= link_to "Skontaktuj się ze mną!", kontakt_path %> </p>
    </div>
</div>

app/views/pages/kontakt.html.erb
<div class="main-container">
    <div class="header left">
        <h2>Kontakt</h2>
    </div>

    <div class="right">
        <p class="text">Interesuje Cię współpraca? Masz pytania?</p>
    
        <p class="text-center">Skontaktuj się ze mną!</p>
        <br>
        <p class="text-center"><i class="fas fa-phone-alt"></i><a href="tel://044589854412"> 0044589854412</a></p>
        <p class="text-center"><i class="fas fa-at"></i><a href="mailto:abcabc@mail.com"> abcabc@mail.com</a></p>
        <br>
        <p>Lub skontaktuj się poprzez formularz:</p>
 
      
            <%= render "contacts/new" %>          
     
    </div>
   
</div>     
 

app/views/pages/o_mnie.html.erb
<div class="main-container">

    <div class="header left ">
        <h2>O mnie</h2>
    </div>
    
    <div class="right">
        <img class="bw  fade-in" src="https://assets.entrepreneur.com/content/3x2/2000/20200130160404-GettyImages-1062463388.jpeg?width=700&crop=2:1" style="width:100%">
        <p class="text fade-in">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum repellat eum quibusdam veritatis placeat dolorum, non suscipit ut ducimus fugiat nulla a ratione. Deleniti quia neque, beatae inventore itaque veniam?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum repellat eum quibusdam veritatis placeat dolorum, non suscipit ut ducimus fugiat nulla a ratione. Deleniti quia neque, beatae inventore itaque veniam?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum repellat eum quibusdam veritatis placeat dolorum, non suscipit ut ducimus fugiat nulla a ratione. Deleniti quia neque, beatae inventore itaque veniam?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum repellat eum quibusdam veritatis placeat dolorum, non suscipit ut ducimus fugiat nulla a ratione. Deleniti quia neque, beatae inventore itaque veniam?</p>
        <p class="fade-in"><i class="fas fa-angle-double-right"></i><%= link_to " Sprawdź, dlaczego warto mi zaufać!", dlaczego_warto_zaufac_path %></p>
        
    </div> 

</div>

app/views/pages/oferta.html.erb
<div class="main-container">
    <div class="header left">
        <h2>Oferta</h2>
    </div>
    <div class="right">
        <div class="cards">
            <div class="card-offer fade-in">
                <div class="card-title">
                    <h4>Content marketing</h4>
                </div>
                <%= image_tag("1.png", crop: :fill, height: 100) %>
                <div class="card-body">
                    <p>Artykuły, poradniki, wpisy na blog, mogą sprzedawać i pozycjonować. A ja wiem co zrobić, aby robiły to dla Ciebie.</p>
                </div>
            </div>
            <div class="card-offer fade-in">
                <div class="card-title">
                    <h4>Content marketing</h4>
                </div>
                 <%= image_tag("2.png", crop: :fill, height: 100) %>   
                <div class="card-body">
                    <p>Artykuły, poradniki, wpisy na blog, mogą sprzedawać i pozycjonować. A ja wiem co zrobić, aby robiły to dla Ciebie.</p>
                </div>
            </div>
            <div class="card-offer fade-in">
                <div class="card-title">
                    <h4>Content marketing</h4>
                </div>
                <%= image_tag("3.png", crop: :fill, height: 100) %>
                <div class="card-body">
                    <p>Artykuły, poradniki, wpisy na blog, mogą sprzedawać i pozycjonować. A ja wiem co zrobić, aby robiły to dla Ciebie.</p>
                </div>
            </div>
            <div class="card-offer fade-in">
                <div class="card-title">
                    <h4>Content marketing</h4>
                </div>
                <%= image_tag("4.png", crop: :fill, height: 100) %>
                <div class="card-body">
                    <p>Artykuły, poradniki, wpisy na blog, mogą sprzedawać i pozycjonować. A ja wiem co zrobić, aby robiły to dla Ciebie.</p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/testimonials/_form.html.erb
<div style="margin: auto; width:85%;">
<p><small>Referencje wyświetlą się na stronie: <%= link_to "Dlaczego warto mi zaufać", dlaczego_warto_zaufac_path %></small> </p>
    <%= simple_form_for(@testimonial) do |f| %>
    <div class="form-inputs">
        <%= f.input :author, label: "Autor" %>
    </div>
    <div class="form-inputs">
        <%= f.input :company, label: "Firma" %>
    </div>
    <div class="form-inputs">
        <%= f.input :link, label: "Link do strony firmy" %>
    </div>
    <div class="form-inputs">
        <%= f.input  :content, label: "Treść", required: true %>
    </div>

    <div class="form-actions">
        <br><br>
        <%= f.button :submit, class:"btn btn-primary" %>
    </div>
    <% end %>
</div>

app/views/testimonials/edit.html.erb
<%= render 'form' %>

app/views/testimonials/new.html.erb
<%= render 'form'%>